name: Publish Python Package to PyPi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    environment:
      name: pypitest

      url: https://test.pypi.org/project/auscopecat/${{ github.event.release.name }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - uses: pdm-project/setup-pdm@v4

    - name: Publish package distributions to PyPI
      run: pdm publish --repository testpypi
