name: Publish Python Package to PyPi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    environment:
      name: pypitest

      url: https://test.pypi.org/project/auscopecat/${{ github.event.release.tag_name }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - uses: pdm-project/setup-pdm@v4

    - name: Read new version number from the tag. expecting the letter 'v' followed by a PEP-440 compliant version number
      env:
        TAG: ${{ github.event.release.tag_name }}
      id: getversionfromtag
      run: echo "VERSION=${TAG#v}" >> $GITHUB_OUTPUT

    - name: check tag name is a valid PEP-440 compliant version number
      run: |
        pip install vercheck
        vercheck ${{ steps.getversionfromtag.outputs.VERSION }} --check-version-number-only

    - name: Write the new version into the project file
      run: |
        sed -i 's/^version =.*/version = "${{ steps.getversionfromtag.outputs.VERSION }}"/' ${{ github.workspace }}/pyproject.toml

    - name: Check the version was correctly updated in the project file
      run: |
        vercheck ${{ steps.getversionfromtag.outputs.VERSION }} ${{ github.workspace }}/pyproject.toml

    - name: Commit changes and more tag to after the version change
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git tag -d ${{ github.event.release.tag_name }}
        git push origin :refs/tags/${{ github.event.release.tag_name }}
        git add ${{ github.workspace }}/pyproject.toml
        git commit -m 'Updated project version to ${{ steps.getversionfromtag.outputs.VERSION }}'
        git push origin
        git tag ${{ github.event.release.tag_name }}
        git push origin ${{ github.event.release.tag_name }}

    - name: Publish package distributions to PyPI
      run: pdm publish --repository testpypi
