name: Build, Test and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - uses: pdm-project/setup-pdm@v4

    - name: Install dependencies
      run: pdm install

    - name: Run tests
      run: pdm run pytest

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'AuScope/AuScope-Cat' && github.ref == 'refs/heads/main' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - uses: pdm-project/setup-pdm@v4

    - name: Publish package distributions to PyPI
      run: pdm publish --repository testpypi
