name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Ruff
      uses: astral-sh/ruff-action@v3
      continue-on-error: true

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        # Install a specific version of uv.
        version: "0.6.3"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
          
    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run tests with coverage
      run: uv run pytest --cov=src --cov-report=xml --cov-report=term

    - name: Generate coverage badge
      run: |
        uv run coverage-badge -f -o .github/badges/coverage.svg

    - name: Deploy coverage badge to main branch
      # Only run on push events to the main branch
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          # The folder the action should deploy.
          folder: .github/badges 
          # The directory to deploy to in the target branch gh-pages
          target-folder: .github/badges
          # Do not remove existing files in the target folder
          clean: false 

    - name: Commit coverage badge to main branch
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .github/badges/coverage.svg
        git commit -m '[skip ci] Updated coverage badge'
        git push

